### ISSUE TITLE
I am getting a error

### ISSUE THREAD

**Issue by albertog** [flutter/friendlychat-steps#26]
only work step_0

Launching lib/main.dart on SM G930F in debug mode...
FAILURE: Build failed with an exception.

* Where:
Build file '/home/albertog/Downloads/friendlychat-steps-master/full_steps/step_1_set_up_firebase/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > Could not resolve all dependencies for configuration ':app:_debugApk'.
         > A problem occurred configuring project ':firebase_analytics'.
            > Could not resolve all dependencies for configuration ':firebase_analytics:_debugPublishCopy'.
               > Could not find com.google.firebase:firebase-auth:10.2.1.
                 Required by:
                     io.flutter.firebase_analytics:firebase_analytics:1.0-SNAPSHOT
               > Could not find com.google.firebase:firebase-analytics:10.2.1.
                 Required by:
                     io.flutter.firebase_analytics:firebase_analytics:1.0-SNAPSHOT
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error running gradle: Exit code 1 from: /home/albertog/android-studio/gradle/gradle-2.14.1/bin/gradle app:properties

FAILURE: Build failed with an exception.

* Where:
Build file '/home/albertog/Downloads/friendlychat-steps-master/full_steps/step_1_set_up_firebase/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > Could not resolve all dependencies for configuration ':app:_debugApk'.
         > A problem occurred configuring project ':firebase_analytics'.
            > Could not resolve all dependencies for configuration ':firebase_analytics:_debugPublishCopy'.
               > Could not find com.google.firebase:firebase-auth:10.2.1.
                 Required by:
                     io.flutter.firebase_analytics:firebase_analytics:1.0-SNAPSHOT
               > Could not find com.google.firebase:firebase-analytics:10.2.1.
                 Required by:
                     io.flutter.firebase_analytics:firebase_analytics:1.0-SNAPSHOT
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by mkhennoussi** [comment]
@albertog  
Make sure all your Android dependencies are up to date (Android Support Repository, etc.). 
The easiest way is to open Android Studio and let it check everything for you (This is what I've done). Then you should be able to follow the codelab.

**Comment by branflake2267** [comment]
A couple other options: 1. run `flutter upgrade`, then test 2. then run `flutter build apk`, look for issues in build. 3. Once you build the apk, you could open it in Android Studio and click on debug. Check the logs in AS. like mkhennoussi said.

**Comment by LarkAscending** [comment]
@albertog Are you still seeing this issue? Is it OK to close it?
