### ISSUE TITLE
Google sign in not completing

### ISSUE THREAD

**Issue by dac3971** [flutter/friendlychat-steps#27]
When I submit my test comment, it gives me the option to use my google account to sign in (a pop up allowing me to select my established google account).  But after I select my account, the pop up disappears and my comment disappears without posting.  My sign in doesn't complete.  Same thing happens on both the virtual device and my connected phone.  I appreciate any help!

**Comment by LarkAscending** [comment]
Assuming this issue is re: Flutter for Firebase codelab:
1. On which step is this happening? Is it Step 6 Sign Users into Your App?
1. Double-check the Step 5 configuration steps.
1. Run `flutter doctor` and paste the output here. If you're on iOS and the tool prompts you to select a Development Team in Xcode, do that.
1. Assuming this is happening in IntelliJ, try running friendlychat from a terminal window using `flutter run --verbose`. Use the -d <device> name argument, if needed, to specify a device. Then try signing into friendlychat again and capture the output from the terminal. 

cc @collinjackson

**Comment by collinjackson** [comment]
It could be an issue with your Firebase configuration (need to enable Google Auth, problematic database access rules, the Firebase app doesn't matching the google-services.json, or the correct signing key isn't uploaded if you're on Android).

Are you on Android or iOS?

**Comment by dac3971** [comment]
Thanks for your responses.

@collinjackson I'm only on Android at the moment.  I definitely enabled Google Auth.  I have database access rules, but I don't think i'm interacting with my database at this exact point (just adding to authorized users).  Not sure where I find the signing key.

@LarkAscending this is happening on step 6.  I carefully went through 5 and 6 to ensure I'm following all steps.  Here is the output from `flutter doctor`:

```
C:\Users\Dave>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], locale en-US, channel alpha)
    • Flutter at C:\Users\Dave\flutter
    • Framework revision e2f54df5ab (6 days ago), 2017-06-02 10:43:54 -0700
    • Engine revision 1f2aa07571
    • Tools Dart version 1.24.0-dev.3.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Dave\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 14.0

[√] Connected devices
    • SAMSUNG SM G530AZ • 0840c01a • android-arm • Android 5.1.1 (API 22)
```

Here is the output after running `flutter run --verbose`.  This is the output at the point where I tap my circle avatar where it prompts me to choose an account for friendlychat:

`[   +15344 ms] E/SpannableStringBuilder( 7264): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[       +3 ms] E/SpannableStringBuilder( 7264): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[      +20 ms] E/flutter ( 7264): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[       +3 ms] E/flutter ( 7264): PlatformException(canceled, 0, null)
[       +2 ms] E/flutter ( 7264): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514)
[       +1 ms] E/flutter ( 7264): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154)
[       +2 ms] E/flutter ( 7264): <asynchronous suspension>
[       +1 ms] E/flutter ( 7264): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:127)
[       +1 ms] E/flutter ( 7264): <asynchronous suspension>
[       +1 ms] E/flutter ( 7264): #3      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:146)
[       +1 ms] E/flutter ( 7264): <asynchronous suspension>
[            ] E/flutter ( 7264): #4      _ensureLoggedIn (file:///C:/Users/Dave/IdeaProjects/friendlychat/lib/main.dart:33)
[       +1 ms] E/flutter ( 7264): <asynchronous suspension>
[            ] E/flutter ( 7264): #5      ChatScreenState._handleSubmitted (file:///C:/Users/Dave/IdeaProjects/friendlychat/lib/main.dart:190)
[       +1 ms] E/flutter ( 7264): <asynchronous suspension>
[       +3 ms] E/flutter ( 7264): #6      ChatScreenState._buildTextComposer.<anonymous closure> (file:///C:/Users/Dave/IdeaProjects/friendlychat/lib/main.dart:171)
[            ] E/flutter ( 7264): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:229)
[            ] E/flutter ( 7264): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:67)
[            ] E/flutter ( 7264): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:151)
[            ] E/flutter ( 7264): #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94)
[            ] E/flutter ( 7264): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:266)
[            ] E/flutter ( 7264): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73)
[            ] E/flutter ( 7264): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
[            ] E/flutter ( 7264): #14     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:124)
[            ] E/flutter ( 7264): #15     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:102)
[            ] E/flutter ( 7264): #16     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:83)
[            ] E/flutter ( 7264): #17     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:42)
[            ] E/flutter ( 7264): #18     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:35)
[            ] E/flutter ( 7264): #19     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:73)
[            ] I/Timeline( 7264): Timeline: Activity_idle id: android.os.BinderProxy@1186e28b time:46559788
`

**Comment by LarkAscending** [comment]
In Step 5, the signing key is the debug signing certificate (SHA-1) described in Configure Firebase for Android. You retrieved it from your development machine and copied it to the dialog in Firebase Console.

This key has to be from the machine you're developing on. If you have both a workstation and a laptop, make sure it matches the one where you're running friendlychat.

**Comment by dac3971** [comment]
@LarkAscending Ah that's likely it.  I misread that direction.  Can I easily get the SHA1 from IntelliJ?

when I type `keytool -exportcert -list -v \
-alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore` in the terminal, I get the response `'keytool' is not recognized as an internal or external command`

**Comment by LarkAscending** [comment]
It's not available in IntelliJ AFAIK. 

Here's [an SO entry](https://stackoverflow.com/questions/19431788/keytool-is-not-recognized-as-an-internal-external-command) on root cause of that error. Briefly:
* the `keytool` executable is located in the `bin` directory of your JDK. You could try running from there.
* your PATH might need updating

**Comment by dac3971** [comment]
Fixed!  Thanks so much @LarkAscending !

**Comment by KaizIqbal** [comment]
@chetan2469 Same Problem here
