### ISSUE TITLE
Failed assertion: line 207 pos 15: 'data != null': is not true

### ISSUE THREAD

**Issue by EasonPai** [flutter/friendlychat-steps#28]
Steps
===
1. pull the latest code from this git
2. I run project of **step_5_data_syncing**
3. get error message
`══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building ChatMessage(dirty):
'package:flutter/src/widgets/text.dart': Failed assertion: line 207 pos 15: 'data != null': is not
true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
#2      new Text (package:flutter/src/widgets/text.dart:207:15)
#3      ChatMessage.build (/Users/easonp/Users/easonp/_home/_dev/flutter/_labs/friendlychat-steps-master/full_steps/step_5_data_syncing/lib/main.dart:97:23)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3446:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3391:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3292:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3371:5)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3366:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4333:14)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2750:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
#14     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:591:20)
#15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2122:19)
#16     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:584:11)
#17     RenderSliverMultiBoxAdaptor.insertAndLayoutChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:282:21)
#18     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1965:58)
#19     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1063:15)
#20     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1965:13)
#21     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:280:5)
#22     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:190:19)
#23     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:233:19)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1869:7)
#25     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:144:11)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1869:7)
#27     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:248:13)
#28     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:882:12)
#29     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:806:20)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1869:7)
#31     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1869:7)
#33     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1869:7)
#35     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1869:7)
#37     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:603:17)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:1869:7)
#39     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124:11)
#40     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:85:7)
#41     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194:7)
#42     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338:14)
#43     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1746:7)
#44     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1041:18)
#45     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:251:19)
#46     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:504:22)
#47     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189:5)
#48     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:688:15)
#49     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:636:9)
#50     _drawFrame (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:70)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════`

4. And the screen on iPhone Simulator
![](https://drive.google.com/uc?export=view&id=0B--vmbY9Aph1ejRqd1RndXc0UGc)

Environment
===

[✓] Flutter (on Mac OS X 10.12.5 16F73, locale zh-Hant-TW, channel alpha)
    • Flutter at /Users/easonp/Users/easonp/_home/_dev/flutter/sdk/flutter
    • Framework revision d36e2f6191 (13 days ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/easonp/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 15.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • iPhone SE • 30D1F9FB-38FC-4E38-8388-37B26B53FF0E • ios • iOS 10.3 (simulator)

**Comment by LarkAscending** [comment]
Can repro this on Android. If your main.dart has the following line of code in ChatScreenState:
`  final List<ChatMessage> _messages = <ChatMessage>[];`

please remove it and restart. (The codelab says to remove the line but that instruction is easy to miss, and the friendlychat-steps sample includes it.)

**Comment by EasonPai** [comment]
So it is, thanks for explanation.
