### ISSUE TITLE
Extra steps in Firebase Console workflow

### ISSUE THREAD

**Issue by LarkAscending** [flutter/friendlychat-steps#35]
Firebase Codelab

Firebase Console has added a Get Started button to the workflow for configuring Database and Storage.

1. To get to Rules section under Database, users need to press Get Started.
1. Users also need to press Get Started in Storage section, or image support doesn't function correctly.

**Comment by LarkAscending** [comment]
Reworked [Step 9 Enable Data Syncing > Configure security rules](https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#8).

@emshack Currently Step 10 Add image support does not tell users to go to Firebase Console > their project > Storage to view the images. It shows them in the app on-device instead. Can you describe what happens with image support for the app if they do not do this extra step and click **Get Started**?

**Comment by emshack** [comment]
Yes, it's important this step gets added. They don't need to view the images on the console, they just need to enable storage by clicking the get started button. If they don't do this, when you try to send an image, it doesn't get sent or show up on device. Nothing happens.

**Comment by LarkAscending** [comment]
Got it. Will work in a visit to the Storage module...

**Comment by LarkAscending** [comment]
Please verify the latest version of the [Image Support step](https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#9).

I was **not** using a new Firebase project, so the change has been spliced in there from a new empty project.

**Comment by emshack** [comment]
LGTM!
