### ISSUE TITLE
IconButton state problem.

### ISSUE THREAD

**Issue by YueWeiwei** [flutter/friendlychat-steps#54]
Hi.

I ran into a problem when I was learning flutter following the code lab samples.
That when I pressed the `Send` button, it's pressed background appeared below the whole `Row` widget. (See the issue image below)

This problem was reproduced when I finished the whole offline practice. And even I cloned a copy from [friendlychat-steps](https://github.com/flutter/friendlychat-steps) and ran it, I got the same problem too.

My device info:
- model `Nexus 5X`
- Android version `7.1.1`

![device-2017-12-23-232438](https://user-images.githubusercontent.com/20765686/34323476-e53f5b64-e885-11e7-8c26-6f0c08bbb632.png)

![device-2017-12-24-085654](https://user-images.githubusercontent.com/20765686/34323529-75edb5e6-e888-11e7-902e-844f2c02c025.png)

**Comment by dramalcolm** [comment]
@YueWeiwei I believe this is a default behavior of the Material Component.

**Comment by duytq94** [comment]
@YueWeiwei wrap it by `Material` widget.

**Comment by hyjfine** [comment]
@duytq94 any details？

**Comment by duytq94** [comment]
@hyjfine I used to stuff the same problem like you, just wrap your button by Material widget will solve.
` Material(
                    child: new Container(
                      margin: new EdgeInsets.symmetric(horizontal: 8.0),
                      child: new IconButton(
                        icon: new Icon(Icons.send),
                        onPressed: () => onSendMessage(textEditingController.text, 0),
                        color: primaryColor,
                      ),
                    ),
                    color: Colors.white,
                  ),
`

**Comment by hyjfine** [comment]
@duytq94 tks, some what it works. It would be fix someday by google i think :)

**Comment by sfshaza2** [comment]
Closing.
