### ISSUE TITLE
Step 1 Android imagepicker not loading

### ISSUE THREAD

**Issue by Pluriscient** [flutter/friendlychat-steps#57]
Problem: 

> 
> After configuring firebase:
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'C:\Developer\Flutter\eventapp\android\build.gradle' line: 27
> 
> * What went wrong:
> Could not determine the dependencies of task ':app:prepareDebugDependencies'.
> > Could not resolve all task dependencies for configuration ':app:_debugApk'.
>    > Could not find com.github.esafirm.android-image-picker:imagepicker:1.5.0.
>      Searched in the following locations:
>          https://jcenter.bintray.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.pom
>          https://jcenter.bintray.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.aar
>          https://maven.google.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.pom
>          https://maven.google.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.aar
>      Required by:
>          project :app > project :image_picker
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org

Solution:
Add this to your project's build.gradle (android/build.gradle)
```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }    # new
        maven {
            url "https://maven.google.com"
        }
    }
}
```
(from https://github.com/esafirm/android-image-picker)

**Comment by sfshaza2** [comment]
About to release an updated version of this codelab and have already updated the code in this repo.  Closing.
