### ISSUE TITLE
FirebaseAnimatedList itemBuilder issue

### ISSUE THREAD

**Issue by wilk3ns** [flutter/friendlychat-steps#59]
Hi! today I tried to build the project but stuck in error like that:

`The argument type '(BuildContext, DataSnapshot, Animation<double>) → ChatMessage' can't be assigned to the parameter type '(BuildContext, DataSnapshot, Animation<double>, int) → Widget'.`

Any suggestions?

P.S. I tried updating all dependencies and plugins

**Comment by Redgeway** [comment]
It seems to be because itemBuilder has an extra parameter called index, so adding in ", _" after Animation<double> would fix it.

Credit: [StackOverflow question here](https://stackoverflow.com/questions/48421889/implementing-codelab-firebase-chat-example)

**Comment by wilk3ns** [comment]
@Redgeway Great! That fixed it. But now I'm facing another one during authentication saying:
`E/flutter (11508): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (11508): type '_Future' is not a subtype of type 'Future<Null>' where
E/flutter (11508):   _Future is from dart:async
E/flutter (11508):   Future is from dart:async
E/flutter (11508):   Null is from dart:core`

**Comment by dramalcolm** [comment]
@wilk3ns the solution to your issue is written up in issue #65

**Comment by arhmnsh** [comment]
`itemBuilder` has a new `index` parameter.
replace the current `itemBuilder` line of code with the updated one:

**`itemBuilder: (_, DataSnapshot snapshot, Animation<double> animation, index) {`**

**Comment by sfshaza2** [comment]
This issue is from the old Flutter/Firebase friendlychat codelab that we no longer support. Closing.
