### ISSUE TITLE
 Issue with android:value in Manifest

### ISSUE THREAD

**Issue by sambhav2612** [flutter/friendlychat-steps#60]
While I was working on the firebase-flutter codelab, the debugging process stomped due to the above problem with the manifest file. I tried many solutions but all in vain. Nothing worked. Please find the link to my repo and screenshot to the issue below:

![screenshot 279](https://user-images.githubusercontent.com/19583619/38102203-31c9081c-33a0-11e8-963d-91b858506d74.png)

Repo: https://github.com/sambhav2612/flutter/tree/master/chat

**Comment by Sfshaza** [comment]
@wmleler, any suggestions?

**Comment by sfshaza2** [comment]
We no longer support the firebase/flutter friendlychat codelab. Closing.
