### ISSUE TITLE
Flutter not working on step 2

### ISSUE THREAD

**Issue by ZaynJarvis** [flutter/friendlychat-steps#61]
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Training\flutter - firebase\full_steps\step_2_sign_in\android\build.gradle' line: 27

* What went wrong:
Could not determine the dependencies of task ':app:prepareDebugDependencies'.
> Could not resolve all task dependencies for configuration ':app:_debugApk'.
   > Could not find com.github.esafirm.android-image-picker:imagepicker:1.5.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.pom
         https://jcenter.bintray.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.aar
         https://maven.google.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.pom
         https://maven.google.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.aar
     Required by:
         project :app > project :image_picker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Finished with error: Gradle build failed: 1

**Comment by JonathanSum** [comment]
Try this. https://github.com/flutter/flutter/issues/14487

**Comment by sfshaza2** [comment]
We no longer support the firebase/flutter friendlychat codelab. Closing.
