### ISSUE TITLE
Unhandled exception: type 'Future<dynamic>' is not a subtype of type 'Future<Null>'

### ISSUE THREAD

**Issue by yagitatsu** [flutter/friendlychat-steps#65]
HI 😃 
It occurs this error on sending message in friendlychat app.
I fixed this by executing `flutter run --no-preview-dart-2`, but could you update this code in order to run on Dart 2.x ?
Maybe, I can fix it, but the website(https://codelabs.developers.google.com/codelabs/flutter-firebase) should be also fixed. So, I submit this issue for now.

It would be happy if you check it.

**Comment by dramalcolm** [comment]
Firebase packages are not yet compatible with dart 2. If you are using Android studio to develop see instructions below:

1. Android Studio>Preferences>Languages & Frameworks>Flutter
2. Set Run application in Dart 2.0 mode to **Disable Dart 2**

**Comment by wilk3ns** [comment]
@yagitatsu @dramalcolm  hi people. Problem is still not solved. Disabling Dart 2 as well as adding _ after Animation is not working now. I'm confused and no idea what to do. I think it is because i'm using latess version of flutter sdk. Think I should use older one.

**Comment by sfshaza2** [comment]
We no longer support the firebase/flutter friendlychat codelab. Closing.
