### ISSUE TITLE
Suggestion:  git branches instead of folders

### ISSUE THREAD

**Issue by Simpler1** [flutter/friendlychat-steps#66]
This tutorial would be easier to work with if it were structured as git branches instead of separate folders.

**Comment by Sfshaza** [comment]
Good point, @Simpler1.

**Comment by sfshaza2** [comment]
I've simplified the structure of this repo. We no longer save the entire project for each step, but only the .dart or pubspec files (when they've changed). Anyway, thanks for the suggestion. (I will be releasing an updated version of this codelab soon.)
