### ISSUE TITLE
Friendly chat tutorial disappear in Google code lab? 

### ISSUE THREAD

**Issue by CircleCurve** [flutter/friendlychat-steps#68]
I look at the google web cache ...and it has changed to another tutorial (baby vote) ?
[Current tutorial link](https://codelabs.developers.google.com/codelabs/flutter-firebase/#1)

[Google web cache for friendly chat](https://webcache.googleusercontent.com/search?q=cache:ugkJTlrKoaIJ:https://codelabs.developers.google.com/codelabs/flutter-firebase/+&cd=1&hl=zh-TW&ct=clnk&gl=hk#2)

![image](https://user-images.githubusercontent.com/8490834/39739154-034e84a8-52c2-11e8-9ec4-1c9d886a995a.png)

Seems like it changes to baby name vote (?
![image](https://user-images.githubusercontent.com/8490834/39739175-1f7e617a-52c2-11e8-9bc5-f6d5f84d62d4.png)

**Comment by vapeurs** [comment]
https://github.com/flutter/friendlychat-steps/issues/71

**Comment by Sfshaza** [comment]
Yes, @CircleCurve, we have changed the codelab. The issue that @vapeurs references has the original codelab, though it seems that the API may be changing.
