### ISSUE TITLE
Step #6: the _name variable cannot be "const"

### ISSUE THREAD

**Issue by travmichwill** [flutter/friendlychat-steps#69]
Just to update the documentation for accuracy:

`const String _name = "Your Name";`

should be changed to

`final String _name = "Your Name";`

The Android Studio designer says:
> Only static fields can be declared as const

**Comment by Sfshaza** [comment]
Yes, thanks for noticing this. Since that doc was last updated, beta 3 launched, which includes Dart 2. Hence this warning. :)

**Comment by sfshaza2** [comment]
Addressed. (I'm about to release an updated version of this codelab.)
