### ISSUE TITLE
Codelabs instructions are missing (Please add them to the repository!)

### ISSUE THREAD

**Issue by Soundbytes** [flutter/friendlychat-steps#71]
Thanks for making the old codelab available. 
It would be very helpful though if the original slides were included as well. 
Can you please add the codelab instructions to the repository? 
This would make the learning experience so much better.
Thanks so much!

**Comment by Sfshaza** [comment]
That's a good point. I will make a point to look for them, but probably not today. Ping this bug if I take too long.  :)

**Comment by Soundbytes** [comment]
As requested here is the bump.
Are the instructions available anywhere on the web? I even tried the waybackmachine without success.

**Comment by Soundbytes** [comment]
Is there any chance that the codelab instructions will be made available? I am stuck with some problems that I presume could be solved with the correct configuration of the firebase project. 
Thanks!

**Comment by vapeurs** [comment]
Unfortunately, no. As mentioned in previous issues.

You can, however follow this Flutter UI tutorial: https://codelabs.developers.google.com/codelabs/flutter/#0

Get a grasp of chat with Firebase realtime DB: https://codelabs.developers.google.com/codelabs/firebase-web/#0

and check out the updated Firebase babyname app to get a sense of the new changes: https://codelabs.developers.google.com/codelabs/flutter-firebase/#0

**Comment by Soundbytes** [comment]
Thanks vapeurs for your suggestions. Regarding the usage of the firestore database in the Babynames codelab: This does not really reflect a change but rather an addition to the toolbox.  AFAIK The firestore realtime database has not been deprecated. Instead users are encouraged to make an informed decision based on the requirements of their app. https://firebase.google.com/docs/database/rtdb-vs-firestore
I find It very unfortunate that the only codelab that features the realtime database in the flutter context has been removed. Is there any reason why flutter users are discouraged from using the realtime database?

**Comment by vapeurs** [comment]
Correct me if I am wrong, but it is my understanding Firestore DB will soon fully replace the realtime DB. 

[img]https://cloud.google.com/images/storage-options/flowchart.svg[/img]

and from this updated flowchart from Google, I no longer see the realtime DB

Here is he previous infographic WITH the realtime DB:

[img]https://cdn-images-1.medium.com/max/1400/1*0iVNXCyFoHREN59CVyQB5w.jpeg[/img]

**Comment by Sfshaza** [comment]
@Soundbytes, thank goodness you pinged me! I tried to find this issue over the weekend.  I found the instructions, and here you go:

[OriginalFirebaseforFlutterCodelab.pdf](https://github.com/flutter/friendlychat-steps/files/2296209/OriginalFirebaseforFlutterCodelab.pdf)

**Comment by vapeurs** [comment]
Than what about this?

**Comment by Soundbytes** [comment]
@Sfshaza 
Thanks so much Shams. You made my Day!

@vapeurs 
>  https://developers.google.com/realtime/deprecation

This refers to a different product. While the Google Realtime API is in fact deprecated the Firebase Realtime DB is definitely not at this moment (and hopefully for a while to come.)

That said I really do appreciate your valuable advice. I need the realtime database to kickstart a small app that will only be used inhouse and I am aware that I will have to migrate to another DB solution sooner or later.
