### ISSUE TITLE
bottom overflowed error

### ISSUE THREAD

**Issue by Zhylkaaa** [flutter/friendlychat-steps#72]
when I try to enter a lot of text the bottom overflowed error appear, I found a solution using constraints: BoxConstraints(maxHeight: 60.0) wrapping TextField with Container 
`Flexible(`
  `            child: Container(`
  `              constraints: BoxConstraints(maxHeight: 60.0),`
   `             child: TextField(`
   `               keyboardType: TextInputType.multiline,`
   `               maxLines: null,`
   `               controller: _textController,`
    `              onChanged: (String text) {`
    `                setState(() {`
     `                 _isComposing = text.length > 0;`
      `              });`
      `            },`
       `           onSubmitted: _isComposing ? _handleSubmitted : null,`
       `           decoration: InputDecoration.collapsed(`
     `               hintText: 'Send a message',`

**Comment by sfshaza2** [comment]
Thanks, @Zhylkaaa. The final step of the codelab fixes the overflow by wrapping the text.
