### ISSUE TITLE
Where is the "Building Beautiful UIs with Flutter" codelab source code?

### ISSUE THREAD

**Issue by vargavince91** [flutter/friendlychat-steps#89]
I found multiple small errors I'd like to propose changes in the Flutter codelabs.

Unfortunately, I didn't find a repo for all of them. I'm looking for the source code for ["Building Beautiful UIs with Flutter"](https://codelabs.developers.google.com/codelabs/flutter/index.html).

I checked the `flutter/website` and `flutter/flutter` repositories and the [Google Codelabs organization](https://github.com/googlecodelabs) and didn't find this particular codelab.

**Comment by sfshaza2** [comment]
@vargavince91, unfortunately the source for the codelab text is not available for the community. I have been updating this sorely outdated codelab and will be releasing an updated version soon.

**Comment by xpat** [comment]
This is related to open issue #93 @sfshaza2 @andrewbury

**Comment by domesticmouse** [comment]
For people who come here through a google search, the location for the codelab's code is https://github.com/flutter/codelabs/tree/master/friendly_chat
