### ISSUE TITLE
Typo in Flutter Animation Step Online

### ISSUE THREAD

**Issue by andrewbury** [flutter/friendlychat-steps#93]
At the link: https://codelabs.developers.google.com/codelabs/flutter/#7

There is a typo where the Duration class is used instead of the parameter "duration" for the AnimationController constructor. Error occurs where you add the AnimationController to the _handleSubmitted method

**Comment by xpat** [comment]
yes
duration:
not 
Duration:

This has already received some attention in issue #89, @sfshaza2 @andrewbury @vargavince91

**Comment by domesticmouse** [comment]
Thank you, I will republish the codelab with a fix for this shortly.
